Blue-Ocean-Naruto/Village-Sports

App.js
client/discover/RenderInterest.jsx
client/discover/index.jsx

- Main Discover component maps interest categories and calls RenderInterests for each
- New component RenderInterests
- Basic functionality to render categorized interests and conditionally render specific interests per category onPress

Discover filters

---

App.js
client/discover/index.jsx

- Created Discover component
- Created stack in App.js

discover framework

---

client/discover/RenderInterest.jsx
client/discover/index.jsx
package-lock.json
package.json
tailwind.config.js

- package.json now includes tailwind dependencies
- **REMEMBER** to run `npm install` after pulling down these changes if you will be rendering the Discover page
- tailwind.config.js is only watching client/discover directory
- Changed location of `key` for each interest category to proper element
- Added some more fake data to see how things render

installed tailwind and added some basic css

---

App.js
client/discover/Recommend.jsx
client/discover/RenderInterest.jsx
client/discover/index.jsx

- New component Recommend
- Including into navigator stack to allow navigation to Recommend screen from both Discover and Map
- Added button in Discover to navigate to Recommend screen

Recommend screen hashed out

---

.gitignore
client/discover/Recommend.jsx
client/discover/index.jsx

- 3 recommended leagues should not fit on screen
- moved button on Discover page to bottom of screen
- added package-lock.json to gitignore

Recommend screen CSS

---

client/discover/Recommend.jsx
client/discover/RenderInterest.jsx
client/discover/index.jsx

- Added Rachel's background gradient (had to add it manually rather than import the shared component to avoid additional flex styling)
- Changed text font to white
- No functional changes

Background gradient to recommended and discover

---

App.js
client/discover/index.jsx
client/home/HomeScreen.jsx
package-lock.json

- Removed default header
- Added Rachel's header
- Change arrow color to white on Recommend page

header options

---

App.js
client/discover/Recommend.jsx
client/discover/index.jsx
client/home/HomeScreen.jsx
package-lock.json

- Incorporated shared component mock data.
- Changed image size for recommend

Discover mockdata

---

client/home/AnnouncementCard.jsx
client/home/Announcements.jsx
client/home/Home.jsx
client/home/HomeScreen.jsx
client/sharedComponents/mockData.js

Styling needs halp
Will work on later after more functionality and bugs are fixed elsewhere

Implemented announcements under Home Page

---

App.js
client/Chat/ChatRoom.jsx
client/Chat/index.jsx
client/home/HomeScreen.jsx
package-lock.json

Now chat room conditionally renders the room the user is in. 
Styling matches better with app.

Added styling and conditional rendering

---

App.js
client/discover/Recommend.jsx
client/discover/RenderInterest.jsx
client/discover/index.jsx

- Added logic to actually recommend leagues based on selected filters
- New state in Recommend to store recommended leagues
- New button in Recommend to navigate to map
- Passing Recommend state to map
- Currently only variable is if a league exists based on key-value `sport`

logic added to recommend stuff

---

client/discover/Recommend.jsx
client/discover/index.jsx

- Forgot to pass navigation as a prop to recommend
- Map button now works in Recommend page

passing navigation to recommend

---

App.js

merged the wrong line in previous PR

---

client/login/Login.jsx
client/login/SignUp.jsx
client/profile/index.jsx
client/sharedComponents/mockData.js

IMPORTANT: (kind of)
The way that Fox was writing his percentages  on button widths "x%%" wasn't compatible with my specific android device so I went ahead and commented them out on my repo. We do want to keep those styles, they're good and they'll be compatible with more modern devices, but I didn't undo that because as soon as I do on my side it makes it so I basically can't develop.
If it's not too much of a hassle, I'd appreciate it if we could keep them commented out for the time being, and then we uncomment them before shipping.

Styled and refactored profile component to match Home-Page and also include interactivity

---

client/discover/Recommend.jsx

- onPress event added to Recommend cards
- Simply passing associated league data to League page

Passing league data to league page

---

client/discover/Recommend.jsx
client/discover/RenderInterest.jsx
client/discover/index.jsx

- Matching home page styling
- Changed button elements to touchableOpacity to allow styling
- Hoping it looks good on iOS

Discover more css

---

client/map/LeagueCard.jsx

- Added a button to direct user to league page from map

connect with league page

---

client/discover/Recommend.jsx
client/discover/RenderInterest.jsx

- explicit rounding of corners in stylesheet.
- hopefully this works on iOS

rounding corners

---

client/discover/Recommend.jsx
client/discover/RenderInterest.jsx

- Added logic to recommend some leagues if no filters are selected
- some more CSS

Recommend with empty filters

---

README.md
client/sharedComponents/mockData.js

- more teams
- announcement time stamps

More mockdata

---

App.js
client/login/Login.jsx
client/login/SignUp.jsx
package-lock.json

Username data is now persisted in firestore. In addition, it is also stored in app.js, and therefore I've changed how the conditional rendering for the stack works a teeeeeny bit as a result.

Username data is now persisted in firestore

---

App.js
client/discover/RenderInterest.jsx
client/home/HomeScreen.jsx

- Should now just be an arrow with a blank title on the Recommend page
- Likewise with the Discover header (no longer shows tab navigator but just a simple back button)
- Changed filter color to green upon selection instead of dark gray

Fixed recommend header

---

App.js
client/home/TempWatchList.jsx
client/wishList/SavedLeagueCard.jsx
client/wishList/TeamList.jsx

- queried leagues from Firestore
- added states in App.js and added in context

Pull leagues from Firestore and create state in App.js

---

App.js
client/Chat/ChatRoom.jsx
client/home/Announcements.jsx

-Chatroom.jsx line 46
-Announcements.jsx line 31

Small changes to code
